# Generated by Django 4.1.1 on 2022-10-01 16:12

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("categories", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=80)),
                ("stock", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("brand", models.CharField(max_length=200)),
                ("weight", models.IntegerField()),
                (
                    "image_url",
                    models.ImageField(
                        blank=True, null=True, upload_to=product.models.upload_to
                    ),
                ),
            ],
        ),
    ]
